### ISSUE TITLE
Fix parsing JSON questions with empty hint

### ISSUE THREAD

**Issue by prokhorovSimbirsoft** [xeurun/quiz-client#13]
Valid JSON for Example:
```
{
   ...
  "questions": [
    {
       ...
      "hint": "hint for question"
    }
  ]
}
```

If filled field `hint` as empty, then parsing the questions throw error and will not work.

Not valid JSON:
```
{
   ...
  "questions": [
    {
       ...
      "hint": ""
    }
  ]
}

```

**Comment by aulisius** [comment]
Hi, I'd like to help with this!

What exactly is the behaviour that needs to be modified?

I've narrowed down the place to [here](https://github.com/xeurun/quiz-client/blob/master/src/Controllers/QuizController.js#L291) for the change. Do I just show a dialog with a message like 'No hint given!' or not allow questions with empty hints?

@xeurun Thoughts?

**Comment by xeurun** [comment]
@aulisius 
Hi, thank you for your interest!  

We have four cases:  

1. `hint` and `hintUrl` are empty - hide hint button or (best choice) show dialog as you suggested 
2. `hint` is empty and `hintUrl` not empty - show a dialog with a message (iframe hidden) 
3. `hint` not empty and `hintUrl` is empty - show a dialog with iframe (message hidden)
4. Both not empty - show both

**Comment by aulisius** [comment]
Got it!

I'll start some work on this and get back to you with the outputs.
